### PR TITLE
Detect PhantomJS.

### PR DESCRIPTION
**Pull request by TeffenEllis**
This PR fixes an issue where PhantomJS isn't detected.

### CODE REVIEW

**Comment by TeffenEllis** [comment]
@5punk,

Test added 😉 

Cheers,
Teffen

**Comment by 5punk** [comment]
@TeffenEllis Thank you for your contribution :)

**Comment by DamonOehlman** [comment]
@5punk thanks for your help curating this PRs :)

I've added you as an npm owner now, so if you wanted to go ahead and bump the minor version (I think this is warranted on every new browser environment that is detected seeing as it technically a new feature) and do a publish of the module I'm completely cool with that.

I still tend to use `npm version` to do this so we get the benefit of the automatic creation of a git tag, and then run the following so I remember to push the tag to github and publish the package at the same time:

```
git push origin master --tags && npm publish
```

**Comment by 5punk** [comment]
I publish my own modules too :)
Thanks, will do.

**Comment by 5punk** [comment]
@TeffenEllis 
`v1.10.0` is now available which will have PhantomJS Detection.

**Pull request merged**
