### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by tomekwi**
Hi, this is a nice and simple library.

We want to use it in a project with a strict quality policy, so I’ve written unit tests for the parsing algorithm itself. The test cases are based on data from my own machines and [a](http://www.useragentstring.com/pages/Browserlist/) [little](http://devblog.blackberry.com/2012/08/blackberry-10-user-agent-string/) [research](https://msdn.microsoft.com/en-us/library/hh869301(v=vs.85).aspx).

Having written the tests, I found a problem with the extracted version number on mobile Safari and fixed that.

I’ve also [extended and updated](https://github.com/DamonOehlman/detect-browser/commit/f7793d8732d679fe9628c69330edbc0f832b0c88) the list of browsers tested on Saucelabs.

### CODE REVIEW

**Comment by tomekwi** [comment]
:bell: If there’s anything I can do to help push this forward, please let me know.

**Comment by DamonOehlman** [comment]
@tomekwi thanks for the reminder.  I really liked the PR when you submitted it, apologies for the delay in merging (have been organising a conference). Will do that now and also add you as a collaborator to the repo :)

**Comment by tomekwi** [comment]
Oh, thanks a lot! That’s an honor! :smiley:

Would you mind if I release the change or do you prefer to do it yourself?

**Comment by DamonOehlman** [comment]
`npm publish` rights granted :) You go for it!

**Comment by tomekwi** [comment]
Many thanks! Released as v1.3.2.

**Pull request merged**
