### PR TITLE
Added code and tests for Opera-Mini, Silk and Chrome OS'

### PR DESCRIPTION
**Pull request by sreya3**
'

### CODE REVIEW

**Comment by 5punk** [comment]
@sreya3 can you add a unit test or two around `ChromeOS` as well?

**Comment by sreya3** [comment]
> @sreya3 can you add a unit test or two around `ChromeOS` as well?

I can though I noticed there are no unit tests for operating systems on the repo. Just for browsers

**Comment by 5punk** [comment]
@DamonOehlman Can you cut a minor release?

**Comment by DamonOehlman** [comment]
@5punk yep - will do.  Sorry only just saw the message.

**Pull request merged**
