### PR TITLE
Chrome webview support

### PR DESCRIPTION
**Pull request by kovacss**
Overview
- 
- Added support for a new Browser `chrome-webview`: https://developer.chrome.com/multidevice/user-agent#webview_user_agent

### CODE REVIEW

**Comment by kovacss** [comment]
I'm not quite sure what browser name would be best suited as this is only works on Android,
Maybe that `android-chrome--webview` or `android-chromium-webview` would be better ?

**Comment by DamonOehlman** [comment]
@kovacss Thanks for the PR.  Ah naming... the age old problem.  I don't think we need the `android-` prefix, but I do wonder if `chromium-webview` might be better.  What do you think?

**Comment by kovacss** [comment]
@DamonOehlman I think you're right, `chromium-webview` might be better. (PR Updated)

**Comment by DamonOehlman** [comment]
@kovacss cool - all looks good to me now.  I'll merge it in and push a version update once #108 is approved and merge.  Thanks for adding this in.

**Pull request merged**
