### PR TITLE
detect react-native

### PR DESCRIPTION
**Pull request by pedrouid**
I noticed that #8 was open for almost 5 years so I thought I would contribute a PR myself

### CODE REVIEW

**Comment by pedrouid** [comment]
This PR could be further improved by expecting a 'react-native' as peer-dependency conditionally and check for Platform.OS to verify whether it's iOS and Android. However I feel the added complexity is unnecessary for this package and this simple check would be enough

**Comment by pedrouid** [comment]
Something I haven't considered is whether document is also undefined for bots but assuming they won't match the `navigator.product` check, I don't think this should conflict

**Comment by DamonOehlman** [comment]
@pedrouid Thanks heaps mate! That issue has been open for a long time and really has needed someone who actively works with `react-native` to take it on, so thanks for doing that.  I'll review the PR in the next day and get it into `master`.

**Comment by DamonOehlman** [comment]
@pedrouid Thanks again for doing this work.  As you can see I've merged the changes into `master`.  I was wondering if prior to me pushing a version update, you would be able to take it for a spin against a react-native app using the dependency of `DamonOehlman/detect-browser`.  If that all works, then I'll push an update.

**Comment by pedrouid** [comment]
Hey @DamonOehlman, where is it published? Could you publish it with a different tag like `rc` or `beta` or `next`?

**Comment by DamonOehlman** [comment]
@pedrouid Good question - I was thinking of back to when I did "old school" pure JS implementations and you could just throw a reference to a github project in the `package.json` and it would resolve to the github `master` branch.  That still works of course, but it doesn't work with a typescript project....

Reading, and then re-reading the logic I think it's safe to publish a new minor version so I'm going to do that now and I'll give you a heads up when it's live.

**Comment by DamonOehlman** [comment]
Done - `5.1.0`

**Pull request merged**
