### PR TITLE
Update detectBrowser.js

### PR DESCRIPTION
**Pull request by gsotirov**
Added support for Chrome on iOS

### CODE REVIEW

**Comment by DamonOehlman** [comment]
@gsotirov Thanks.  Just wondering if you have a sample user agent string that you could include in the [tests](https://github.com/DamonOehlman/detect-browser/blob/master/test/logic.js) so we can ensure that everything continues to work with any future changes.

**Comment by gsotirov** [comment]
Ok, Damon, I'll do that :)

**Comment by gsotirov** [comment]
Done.

**Comment by DamonOehlman** [comment]
@gsotirov Thanks - merged and published as `1.5.0`

**Pull request merged**
